# @host=http://www.congb19.top/api
# @host=http://localhost:8001/api
@host=http://146.56.224.139:4000/v1/graphql

# GET {{host}}

POST {{host}}
content-type: application/json;charset=UTF-8

{
  "query": "query MyQuery {jh_bbs_comments {id}}"
}

  # "operationName": "MyQuery",
  # "variables": null,

# http://47.101.42.80:8001/api/public/getDate
# http://47.101.42.80:8001/api/public/getLuckyNumber

# http://localhost:8001/api/json

# http://localhost:8001/api/public/getDate
# http://localhost:8001/api/public/getLuckyNumber

# http://www.congb19.top/api/public/getDate
# POST {{host}}/public/createTrashArticle
# content-type: application/json;charset=UTF-8

# {
#   "main": "橘子",
#   "event": "很好吃",
#   "anotherEvent": "橘子酸酸甜甜的"
# }

# GET http://qa.edusoho.cn/api/resource_favorite

# GET http://discuz.1inf0.com/api/forum?include=users
